config/routes.rb
XmlTest::Application.routes.draw do

  resources :agents
  match 'agent_property/:id/property' => 'agent_properties#show', :as => :property
  match 'xml_with_error' => 'agent_properties#xml_errors', :as => :xml_with_errors
  root :to => 'agents#index'
end

app/models/agent.rb
class Agent < ActiveRecord::Base
  has_many :agent_properties
  has_many :properties, :through => :agent_properties

end

app/models/agent_property.rb
class AgentProperty < ActiveRecord::Base
  belongs_to :agent
  belongs_to :property
  has_many :property_values

  attr_accessible :status, :update_count, :property
end

app/models/property.rb
class Property < ActiveRecord::Base

  attr_accessible :name
end

app/models/property_value.rb
class PropertyValue < ActiveRecord::Base
  belongs_to :agent_property, :foreign_key => 'agent_property_id'

  attr_accessible :value
end

app/controllers/agent_properties_controller.rb
class AgentPropertiesController < ApplicationController

  def show
    @values = PropertyValue.where(:agent_property_id => params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @values }
    end
  end

  def xml_errors
    @xml_with_errors = AgentProperty.where(:agent_id => nil)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @xml_with_errors }
    end
  end

end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController

  def index
    @agents = Agent.all
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
    @agent = Agent.find(params[:id])
    @agent_properties = @agent.agent_properties

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agent }
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agent_properties/show.html.erb
<h1>Agent Property changes list</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Id</th>
    <th>Value</th>
  </tr>
  </thead>
  <tbody>
  <% @values.each do |property_value| %>
      <tr>
        <td><%= property_value.id %></td>
        <td><%= property_value.value %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn'  %>
</div>

app/views/agent_properties/xml_errors.html.erb
<h1>Xml With Errors</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Id</th>
    <th>XML</th>
    <th>Error</th>
  </tr>
  </thead>
  <tbody>
  <% @xml_with_errors.each do |property| %>
      <tr>
        <td><%= property.id %></td>
        <td><%= property.property_values.first.value unless property.property_values.first.nil? %></td>
        <td><%= property.status %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/agents/_form.html.erb
<%= form_for @agent, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :agent_unique_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :agent_unique_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                agents_path, :class => 'btn' %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<%- model_class = Agent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agents/index.html.erb
<%- model_class = Agent -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:agent_unique_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= agent.agent_unique_id %></td>
        <td><%= agent.name %></td>
        <td><%= link_to 'Show', agent_path(agent), :class => 'btn' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to t('.View xml with errors', :default => 'View xml with Errors'),
              xml_with_errors_path, :class => 'btn'  %>
</div>

app/views/agents/new.html.erb
<%- model_class = Agent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agents/show.html.erb
<%- model_class = Agent -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:agent_unique_id) %>:</strong></dt>
  <dd><%= @agent.agent_unique_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @agent.name %></dd>
  <dt><strong><%= model_class.human_attribute_name('Properties') %></strong></dt>
</dl>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Status</th>
    <th>Update Count</th>
    <th>View Complete Changes</th>
  </tr>
  </thead>
  <tbody>
  <% @agent_properties.each do |agent_property| %>
      <tr>
        <td><%= agent_property.id %></td>
        <td><%= agent_property.property.name %></td>
        <td><%= agent_property.status %></td>
        <td><%= agent_property.update_count %></td>
        <td><%= link_to 'View', property_url(:id => agent_property.id)%></td>
      </tr>
  <% end %>
  </tbody>
</table>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              xml_with_errors_path, :class => 'btn'  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>